/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/mufeng889/elegant-router
// Vue auto route: https://github.com/soybeanjs/elegant-router


import type { LazyRouteFunction, RouteObject } from "react-router-dom";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";
type CustomRouteObject = Omit<RouteObject, 'Component'|'index'> & {
  Component?: React.ComponentType<any>|null;
};

export const layouts: Record<RouteLayout, LazyRouteFunction<CustomRouteObject>> = {
  base: () => import("@/layouts/base-layout/index.tsx"),
  blank: () => import("@/layouts/blank-layout/index.tsx"),
};

export const pages: Record<LastLevelRouteKey, LazyRouteFunction<CustomRouteObject>> = {
  403: () => import("@/pages/_builtin/403/index.tsx"),
  404: () => import("@/pages/_builtin/404/index.tsx"),
  500: () => import("@/pages/_builtin/500/index.tsx"),
  "iframe-page": () => import("@/pages/_builtin/iframe-page/[url].tsx"),
  about: () => import("@/pages/about/index.tsx"),
  "function_hide-child_one": () => import("@/pages/function/hide-child/one/index.tsx"),
  "function_hide-child_three": () => import("@/pages/function/hide-child/three/index.tsx"),
  "function_hide-child_two": () => import("@/pages/function/hide-child/two/index.tsx"),
  "function_multi-tab": () => import("@/pages/function/multi-tab/index.tsx"),
  function_request: () => import("@/pages/function/request/index.tsx"),
  "function_super-page": () => import("@/pages/function/super-page/index.tsx"),
  function_tab: () => import("@/pages/function/tab/index.tsx"),
  "function_toggle-auth": () => import("@/pages/function/toggle-auth/index.tsx"),
  home: () => import("@/pages/home/index.tsx"),
  "login_code-login": () => import("@/pages/login/code-login/index.tsx"),
  login: () => import("@/pages/login/index.tsx"),
  "login_pwd-login": () => import("@/pages/login/pwd-login/index.tsx"),
  login_register: () => import("@/pages/login/register/index.tsx"),
  "login_reset-pwd": () => import("@/pages/login/reset-pwd/index.tsx"),
  manage_menu: () => import("@/pages/manage/menu/index.tsx"),
  manage_role: () => import("@/pages/manage/role/index.tsx"),
  "manage_user-detail": () => import("@/pages/manage/user-detail/[id].tsx"),
  manage_user: () => import("@/pages/manage/user/index.tsx"),
  "multi-menu_first_child": () => import("@/pages/multi-menu/first_child/index.tsx"),
  "multi-menu_second_child_home": () => import("@/pages/multi-menu/second_child_home/index.tsx"),
  "user-center": () => import("@/pages/user-center/index.tsx"),
};
